mybatis:
  type-aliases-package: com.hust
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hustdb?useSSL=true&useUnicode=true&autoReconnect=true&characterEncoding=utf-8&serverTimezone=GMT
    username: root
    password: lf123456
    driver-class-name: com.mysql.cj.jdbc.Driver
