# MyBatis 配置
mybatis:
  type-aliases-package: com.hust.pojo
  mapper-locations: classpath:dao/*.xml
  configuration:
    map-underscore-to-camel-case: true
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hustdb?useSSL=true&useUnicode=true&autoReconnect=true&characterEncoding=utf-8&serverTimezone=GMT
    username: root
    password: lf123456
    driver-class-name: com.mysql.cj.jdbc.Driver
